"""
Pydantic schemas for messages exchanged between frontend and backend.
"""

from typing import Optional, List, Any, Dict
from pydantic import BaseModel, Field
from enum import Enum
from datetime import datetime
import uuid


class MessageRole(str, Enum):
    """Role of the message sender."""
    USER = "user"
    ASSISTANT = "assistant"
    SYSTEM = "system"
    TOOL = "tool"


class MessageType(str, Enum):
    """Type of WebSocket message."""
    USER_MESSAGE = "user_message"
    ASSISTANT_CHUNK = "assistant_chunk"
    ASSISTANT_MESSAGE = "assistant_message"
    TOOL_CALL = "tool_call"
    TOOL_RESULT = "tool_result"
    PLAN = "plan"
    TASK_UPDATE = "task_update"
    ERROR = "error"
    STATUS = "status"
    STREAM_START = "stream_start"
    STREAM_END = "stream_end"


class ChatMessage(BaseModel):
    """A single chat message."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    role: MessageRole
    content: str
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    metadata: Dict[str, Any] = Field(default_factory=dict)


class WebSocketMessage(BaseModel):
    """Message format for WebSocket communication."""
    type: MessageType
    content: Any
    session_id: str
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    metadata: Dict[str, Any] = Field(default_factory=dict)


class UserInput(BaseModel):
    """User input from the frontend."""
    message: str
    session_id: Optional[str] = None


class PlanStep(BaseModel):
    """A single step in an execution plan."""
    step_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    type: str  # "tool" or "agent"
    tool: Optional[str] = None
    task: Optional[str] = None
    input: Optional[Dict[str, Any]] = None
    reasoning: str = ""


class ExecutionPlan(BaseModel):
    """A structured plan generated by the planner agent."""
    plan_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    query: str
    steps: List[PlanStep]
    reasoning: str = ""
