"""
Plan schemas — structured plans generated by the planner agent.
"""

from typing import Optional, List, Dict, Any
from pydantic import BaseModel, Field
import uuid


class PlanStep(BaseModel):
    step_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    type: str  # "tool" or "agent"
    tool: Optional[str] = None
    task: Optional[str] = None
    input: Optional[Dict[str, Any]] = None
    depends_on: List[str] = Field(default_factory=list)
    reasoning: str = ""


class ExecutionPlan(BaseModel):
    plan_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    query: str
    steps: List[PlanStep] = Field(default_factory=list)
    reasoning: str = ""
    direct_response: Optional[str] = None
